import type { Metadata } from "next";
import { title, text } from "./fonts";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={cn("h-full", "antialiased", "bg-neutral-50", title.variable, text.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-screen flex flex-col px-10">
        <Header />
        <main className="flex-1 pb-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
